### ISSUE TITLE
Installation at non-root url path

### ISSUE THREAD

**Issue by Chaz6** [schollz/cowyo#162]
I would like to run cowyo behind a proxy, accessed from a path such as `/app/f7a7faa8-f77f-4f62-a39c-f5b2d670f872` however when I try to access the url, the browser is redirected to a url like `/PreviousPlatypus` which returns 404 since it is not available at that location.

This my `docker-compose.yml`:-

```
version: "3"
services:
  cowyo_app:
    container_name: cowyo
    image: "schollz/cowyo:latest"
    restart: always
    volumes:
      - "./data:/data:Z"
    ports:
      - "9005:8050"
```

This is the relevant config for nginx:-

```
# cowyn app
location ^~ /app/f7a7faa8-f77f-4f62-a39c-f5b2d670f872/ {
  proxy_pass http://127.0.0.1:9005/;
}
```
